spring.application.name=smartmunicipal
# PostgreSQL Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/smart_municipal_db
spring.datasource.username=postgres
spring.datasource.password=Malee@1985

# Hibernate JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Server Port
server.port=8080