package com.itum.smartmunicipal.payment.service;

import com.itum.smartmunicipal.payment.entity.Payment;
import com.itum.smartmunicipal.payment.repository.PaymentRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.time.LocalDateTime;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.UUID;

@Service
public class PaymentService {

    @Autowired
    private PaymentRepository paymentRepository;

    // --- Citizen Services ---

    public List<Payment> getPendingPaymentsByCitizen(String citizenId) {
        return paymentRepository.findByCitizenIdAndStatus(citizenId, "PENDING");
    }

    public List<Payment> getPaymentHistoryByCitizen(String citizenId) {
        return paymentRepository.findByCitizenIdOrderByPaymentDateDesc(citizenId);
    }

    public Payment processPayment(Long paymentId) {
        Payment payment = paymentRepository.findById(paymentId)
                .orElseThrow(() -> new RuntimeException("Payment record not found"));

        // Mocking a successful payment gateway integration
        payment.setStatus("SUCCESS");
        payment.setTransactionId("#TXN-" + UUID.randomUUID().toString().substring(0, 8).toUpperCase());
        payment.setPaymentDate(LocalDateTime.now());

        return paymentRepository.save(payment);
    }

    // --- Admin Services ---

    // NEW METHOD ADDED HERE: Save a new bill/fine generated by the Admin
    public Payment savePayment(Payment payment) {
        return paymentRepository.save(payment);
    }

    public List<Payment> getAllTransactions() {
        return paymentRepository.findAll();
    }

    public Map<String, Object> getAdminKPIs() {
        Map<String, Object> kpis = new HashMap<>();

        Double totalRevenue = paymentRepository.calculateTotalRevenue();
        Double pendingCollections = paymentRepository.calculatePendingCollections();
        long successCount = paymentRepository.countSuccessfulTransactions();
        long totalCount = paymentRepository.count();

        double successRate = totalCount == 0 ? 0.0 : ((double) successCount / totalCount) * 100;

        kpis.put("totalRevenue", totalRevenue != null ? totalRevenue : 0.0);
        kpis.put("pendingCollections", pendingCollections != null ? pendingCollections : 0.0);
        kpis.put("successRate", String.format("%.1f", successRate) + "%");

        return kpis;
    }
}