
spring.datasource.url=jdbc:postgresql://localhost:5432/municipal_db
spring.datasource.username=postgres
spring.datasource.password=Thuvi@06
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true